### ISSUE TITLE
Cookie 설명에서의 서버 부담 증가

### ISSUE THREAD

**Issue by SausageMania** [Esoolgnah/Frontend-Interview-Questions#4]
https://github.com/Esoolgnah/Frontend-Interview-Questions/blob/main/Notes/important-4/web-storage.md

cookie는 브라우저에 저장한다는 점에서 서버에 값을 저장하는 session에 비해 서버부담이 비교적 적습니다.
물론 cookie도 request header를 통해 서버에 데이터를 전송한다는 점에서 서버부하가 발생할 수는 있지만, 글의 의도상 서버 부담 증가는 session에 관한 설명을 말씀하신 것 같습니다..!

session에 대한 설명 문구를 추가해주시면 다른 분들이 이해하기 더 좋을 것 같습니다.

+ 글 잘 읽었습니다. 정리된 글 덕에 수월하게 복습할 수 있었네요. 감사합니다.

**Comment by Esoolgnah** [comment]
좋은 피드백 감사합니다!
말씀하신대로 쿠키에 적힌 서버부담 증가가 혼란을 야기할 수 있는 부분인 것 같아
쿠키에 대한 설명에 세션을 추가하고, 서버 부담이 증가할 수 있는 이유를 함께 추가하였습니다.
또 고쳐야할 부분 있을 시 언제든 제보 부탁드려요! 다시금 감사드립니다.🙇🏻‍♂️

**Comment by Esoolgnah** [comment]
> https://github.com/Esoolgnah/Frontend-Interview-Questions/blob/main/Notes/important-4/web-storage.md
> 
> cookie는 브라우저에 저장한다는 점에서 서버에 값을 저장하는 session에 비해 서버부담이 비교적 적습니다. 물론 cookie도 request header를 통해 서버에 데이터를 전송한다는 점에서 서버부하가 발생할 수는 있지만, 글의 의도상 서버 부담 증가는 session에 관한 설명을 말씀하신 것 같습니다..!
> 
> session에 대한 설명 문구를 추가해주시면 다른 분들이 이해하기 더 좋을 것 같습니다.
> 
> * 글 잘 읽었습니다. 정리된 글 덕에 수월하게 복습할 수 있었네요. 감사합니다.

좋은 피드백 감사합니다!
말씀하신대로 쿠키에 적힌 서버부담 증가가 혼란을 야기할 수 있는 부분인 것 같아
쿠키에 대한 설명에 세션을 추가하고, 서버 부담이 증가할 수 있는 이유를 함께 추가하였습니다.
또 고쳐야할 부분 있을 시 언제든 제보 부탁드려요! 다시금 감사드립니다.🙇🏻‍♂️
